# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Kiwi

target 'ObjCTests' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APCreature
  pod 'Kiwi', '~> 2.4.0'

end
